# Subsetting {#subset}

```{r include=FALSE}
library(tidyverse)
```


From <https://www.r-bloggers.com/5-ways-to-subset-a-data-frame-in-r/>

Note: since this is down for maintenance, I will turn off evaluation on these chunks: 

```{r}
education <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/robustbase/education.csv", stringsAsFactors = FALSE)

colnames(education) <- c("X","State","Region","Urban.Population","Per.Capita.Income","Minor.Population","Education.Expenditures")

glimpse(education)

```

## Subsetting using brackets

```{r}
education[c(10:21),c(2,6:7)]
```

## Subset using brackets by omitting the rows and columns we don’t want

```{r}
education[-c(1:9,22:50),-c(1,3:5)]
```

## Subset using brackets in combination with the which() function and the %in% operator

```{r}
education[which(education$Region == 2),names(education) %in% c("State","Minor.Population","Education.Expenditures")]
```

## Subset using the subset() function

```{r}
subset(education, Region == 2, select = c("State","Minor.Population","Education.Expenditures"))
```

## Subset using dyplyr's filter() and select()

```{r}
select(filter(education, Region == 2),c(State,Minor.Population:Education.Expenditures))
```



